#!/usr/bin/env bash

eval "$(/opt/homebrew/bin/brew shellenv)"

eval "$(tv init zsh)"

export FZF_CTRL_T_COMMAND="rg --hidden --files"
export FZF_DEFAULT_COMMAND="rg --hidden --files"
export FZF_DEFAULT_OPTS='--preview="bat --style=numbers --color=always --line-range :500 {}"'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [ -f ~/.shell/plugins.local ]; then
    source ~/.shell/plugins.local
fi
