#!/usr/bin/env bash

eval "$(/opt/homebrew/bin/brew shellenv)"

export FZF_CTRL_T_COMMAND="rg --hidden --files"
export FZF_DEFAULT_COMMAND="rg --hidden --files"
export FZF_DEFAULT_OPTS='--preview="bat --style=numbers --color=always --line-range :500 {}"'

# https://stackoverflow.com/questions/69012676/install-older-ruby-versions-on-a-m1-macbook/69012677#69012677
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
export LDFLAGS="-L/usr/local/opt/readline/lib"
export CPPFLAGS="-I/usr/local/opt/readline/include"
export PKG_CONFIG_PATH="/usr/local/opt/readline/lib/pkgconfig"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [ -f ~/.shell/plugins.local ]; then
    source ~/.shell/plugins.local
fi
