GOOSE_PROVIDER: claude-code
GOOSE_MODE: approve
extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  context7:
    args:
      - -y
      - '@upstash/context7-mcp'
    bundled: null
    cmd: npx
    description: Context7 MCP server for up-to-date code and docs
    enabled: true
    env_keys: []
    envs: {}
    name: context7
    timeout: 300
    type: stdio
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  filesystem:
    args:
      - -y
      - '@modelcontextprotocol/server-filesystem'
      - /Users/markfaga
    bundled: null
    cmd: npx
    description: filesystem MCP Server
    enabled: true
    env_keys: []
    envs: {}
    name: filesystem
    timeout: 300
    type: stdio
  git:
    args:
      - mcp-server-git
    bundled: null
    cmd: uvx
    description: Git version control system integration
    enabled: true
    env_keys: []
    envs: {}
    name: git
    timeout: 300
    type: stdio
  jetbrains:
    bundled: true
    display_name: Jetbrains
    enabled: false
    name: jetbrains
    timeout: 300
    type: builtin
  memory:
    bundled: true
    display_name: Memory
    enabled: true
    name: memory
    timeout: 300
    type: builtin
  pdfreader:
    args:
      - mcp-read-pdf
    bundled: null
    cmd: uvx
    description: Read large and complex PDF documents
    enabled: true
    env_keys: []
    envs: {}
    name: pdfreader
    timeout: 300
    type: stdio
  tutorial:
    bundled: true
    display_name: Tutorial
    enabled: true
    name: tutorial
    timeout: 300
    type: builtin
GOOSE_MODEL: claude-3-5-sonnet-latest
