#!/usr/bin/env bash

# FZF Configurations
ff() { local file; file=$(fzf) && [[ -e "$file" ]] && vim "$file"; }

if [[ "$TERM_PROGRAM" != "WarpTerminal" ]]; then
  fzf-file-open-widget() {
    local output
    output=$(__fzf_select) && vim "${output:0:-1}" < /dev/tty

    local ret=$?
    zle reset-prompt
    return $ret
  }
  zle     -N   fzf-file-open-widget
  bindkey '\C-f' fzf-file-open-widget
fi

if [ -f ~/.zsh/plugins.local ]; then
    source ~/.zsh/plugins.local
fi
