#!/usr/bin/env bash

export FZF_DEFAULT_COMMAND="rg --hidden --files"
export FZF_DEFAULT_OPTS='--preview="bat --style=numbers --color=always --line-range :500 {}"'

# # FZF Configurations
# bind -x '"\C-f": FZF_FILE=$(fzf) && [[ -e $FZF_FILE ]] && vim $FZF_FILE;'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


if [ -f ~/.zsh/plugins.local ]; then
    source ~/.zsh/plugins.local
fi
