#!/usr/bin/env bash

# Save history to a file
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history

# More data in history file
setopt EXTENDED_HISTORY
# share history across multiple zsh sessions
setopt SHARE_HISTORY
# append to history
setopt APPEND_HISTORY
# adds commands as they are typed, not at shell exit
setopt INC_APPEND_HISTORY
# do not store duplications
setopt HIST_IGNORE_DUPS
# removes blank lines from history
setopt HIST_REDUCE_BLANKS
# confirm history substitution command before executing it
setopt HIST_VERIFY

# enable zsh correction when mistyping prompts
setopt CORRECT
setopt CORRECT_ALL

# Case-insensitive globbing (used in pathname expansion)
setopt NO_CASE_GLOB

# Automatically navigate to paths without typing `cd`
setopt AUTO_CD

autoload edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

if [ -f ~/.zsh/settings.local ]; then
    source ~/.zsh/settings.local
fi
