#!/usr/bin/env bash

# FZF Configurations
bind -x '"\C-f": FZF_FILE=$(fzf) && [[ -e $FZF_FILE ]] && vim $FZF_FILE;'

# asdf configurations
. /usr/local/opt/asdf/libexec/asdf.sh
. $HOME/.asdf/plugins/java/set-java-home.bash
# . $HOME/.asdf/completions/asdf.bash

if [ -f ~/.bash/plugins.local ]; then
    source ~/.bash/plugins.local
fi
